# Generated by Django 4.1.5 on 2023-01-30 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(0)])),
                ('age_to', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='this is the price per 100 unit coverage per annum', max_digits=10)),
                ('charge', models.IntegerField(help_text='Percentage value (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Age Groups',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPolicy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Quoted'), (3, 'Active Policy'), (4, 'Archived')], default='1')),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical policy',
                'verbose_name_plural': 'historical policys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Quoted'), (3, 'Active Policy'), (4, 'Archived')], default='1')),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['id', 'slug'], name='policy_poli_id_e5526b_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['name'], name='policy_poli_name_f76345_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['-created'], name='policy_poli_created_2036e6_idx'),
        ),
        migrations.AddField(
            model_name='historicalpolicy',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agegrouppolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='policy.policy'),
        ),
        migrations.AddIndex(
            model_name='agegrouppolicy',
            index=models.Index(fields=['id'], name='policy_ageg_id_3f9a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='agegrouppolicy',
            index=models.Index(fields=['-created'], name='policy_ageg_created_58cae3_idx'),
        ),
    ]
